/* =====================================================================
   BANCO DE PREGUNTAS DEL SIMULACRO — CLF-C02
   d = dominio (1..4). a = índice o array de índices (multirespuesta).
   ===================================================================== */
const EXAM_BANK = [
/* ---------------- Dominio 1 · Conceptos de la nube (24 %) ---------------- */
{d:1,q:'¿Qué ventaja de la computación en la nube permite a una empresa dejar de invertir por adelantado en centros de datos?',
 o:['Cambiar gastos de capital por gastos variables','Aumentar la tolerancia a fallos','Mejorar la latencia global','Reducir el número de usuarios de IAM'],a:0,
 why:'Es la primera de las seis ventajas: pagas solo por lo que consumes en lugar de invertir en hardware.'},
{d:1,q:'Una empresa quiere lanzar su aplicación en Europa, Asia y América en pocos clics. ¿Qué ventaja de la nube aprovecha?',
 o:['Ser global en minutos','Economías de escala','Dejar de adivinar la capacidad','Gastos variables'],a:0,
 why:'Desplegar en varias Regiones reduce la latencia para usuarios de todo el mundo casi de inmediato.'},
{d:1,q:'¿Qué modelo de servicio en la nube ofrece Amazon EC2?',
 o:['IaaS','PaaS','SaaS','DaaS'],a:0,
 why:'EC2 entrega infraestructura: el cliente gestiona el sistema operativo y todo lo que hay por encima.'},
{d:1,q:'Una empresa mantiene su ERP en su propio centro de datos y ejecuta el resto de sus aplicaciones en AWS. ¿Qué modelo de implementación es?',
 o:['Híbrido','Nube pública','On-premises','Multirregión'],a:0,
 why:'Combinar recursos locales con recursos en la nube define el modelo híbrido.'},
{d:1,q:'¿Qué estrategia de migración consiste en mover una aplicación a la nube sin modificarla?',
 o:['Rehost','Refactor','Repurchase','Retire'],a:0,
 why:'Rehost es el lift and shift, la vía más rápida cuando el tiempo apremia.'},
{d:1,q:'¿Cuáles son DOS pilares del AWS Well-Architected Framework? (elige dos)',
 o:['Excelencia operativa','Optimización de costos','Elasticidad','Interoperabilidad'],a:[0,1],multi:true,
 why:'Los seis pilares: excelencia operativa, seguridad, fiabilidad, eficiencia del rendimiento, optimización de costos y sostenibilidad.'},
{d:1,q:'Una arquitectura usa colas de mensajes entre sus componentes. ¿Qué principio de diseño aplica?',
 o:['Desacoplamiento de componentes','Escalado vertical','Consistencia fuerte','Colocation'],a:0,
 why:'Desacoplar evita que el fallo o la lentitud de un componente arrastre a los demás.'},
{d:1,q:'¿Qué describe mejor la elasticidad en AWS?',
 o:['Aprovisionar y liberar recursos automáticamente según la demanda','Replicar datos en tres AZ','Cifrar los datos en reposo','Reducir la latencia con una CDN'],a:0,
 why:'La elasticidad ajusta la capacidad hacia arriba y hacia abajo de forma automática.'},
{d:1,q:'¿Qué herramienta revisa cargas de trabajo frente a las mejores prácticas de AWS y genera un plan de mejora?',
 o:['AWS Well-Architected Tool','AWS Config','AWS Artifact','AWS Budgets'],a:0,
 why:'Está disponible sin coste en la consola de AWS.'},
{d:1,q:'¿Qué define el RTO de una aplicación?',
 o:['El tiempo máximo aceptable de interrupción','La cantidad de datos que se puede perder','El coste mensual','El número de usuarios simultáneos'],a:0,
 why:'RTO es el objetivo de tiempo de recuperación; RPO es el de punto de recuperación (datos).'},
{d:1,q:'¿Qué perspectiva del AWS Cloud Adoption Framework aborda la formación y el cambio cultural?',
 o:['Personas','Plataforma','Gobernanza','Operaciones'],a:0,
 why:'La perspectiva de personas cubre competencias, roles y gestión del cambio.'},
{d:1,q:'¿Qué servicio ayuda a inventariar servidores on-premises antes de una migración?',
 o:['AWS Application Discovery Service','AWS Config','AWS CloudTrail','Amazon Inspector'],a:0,
 why:'Recopila datos de configuración, uso y dependencias del entorno local.'},
{d:1,q:'Una organización quiere reducir el impacto medioambiental de sus cargas. ¿Qué pilar del framework le orienta?',
 o:['Sostenibilidad','Fiabilidad','Seguridad','Excelencia operativa'],a:0,
 why:'El pilar de sostenibilidad guía la eficiencia energética y de recursos.'},
{d:1,q:'¿Qué opción describe el escalado horizontal?',
 o:['Añadir más instancias del mismo tipo','Cambiar a una instancia con más CPU','Aumentar el tamaño del volumen EBS','Migrar a otra Región'],a:0,
 why:'Scale out añade nodos; scale up aumenta el tamaño de un nodo.'},
{d:1,q:'¿Qué servicio permite ejecutar servicios de AWS dentro del centro de datos del cliente?',
 o:['AWS Outposts','AWS Direct Connect','AWS Local Zones','AWS Snowball'],a:0,
 why:'Outposts extiende la infraestructura de AWS a las instalaciones del cliente.'},
{d:1,q:'¿Qué estrategia de recuperación ante desastres ofrece el RTO más bajo y el mayor coste?',
 o:['Multi-site activo-activo','Backup y restauración','Pilot light','Warm standby'],a:0,
 why:'Activo-activo mantiene el servicio completo en dos ubicaciones a la vez.'},
{d:1,q:'¿Cuál es el beneficio de usar servicios gestionados de AWS frente a instalar el software en EC2?',
 o:['Reducir la carga operativa de parcheo y mantenimiento','Eliminar el modelo de responsabilidad compartida','Obtener soporte Enterprise gratuito','Suprimir los costes de transferencia de datos'],a:0,
 why:'Los servicios gestionados trasladan a AWS tareas indiferenciadas como parcheo y copias.'},
{d:1,q:'¿Qué concepto compara todos los costes de operar on-premises frente a la nube, incluyendo energía y personal?',
 o:['TCO','SLA','RPO','KPI de red'],a:0,
 why:'El coste total de propiedad es el argumento habitual del caso de negocio de migración.'},
{d:1,q:'¿Qué caracteriza a AWS Elastic Beanstalk?',
 o:['Despliega y escala aplicaciones web sin que gestiones la infraestructura','Es una base de datos NoSQL','Es un servicio de red privada','Es un almacén de objetos'],a:0,
 why:'Beanstalk es la opción PaaS de AWS: subes el código y se encarga del resto.'},
{d:1,q:'¿Qué servicio replica bases de datos hacia AWS manteniendo el origen en funcionamiento?',
 o:['AWS Database Migration Service','AWS DataSync','AWS Snowcone','AWS Glue'],a:0,
 why:'DMS minimiza el tiempo de inactividad durante la migración.'},

/* ---------------- Dominio 2 · Seguridad y cumplimiento (30 %) ---------------- */
{d:2,q:'Según el modelo de responsabilidad compartida, ¿de qué es responsable el cliente al usar Amazon EC2?',
 o:['De parchear el sistema operativo invitado','De la seguridad física del centro de datos','Del hipervisor','Del hardware de red'],a:0,
 why:'AWS asegura la infraestructura; el cliente asegura el sistema operativo, las aplicaciones y los datos.'},
{d:2,q:'¿Cuál es la práctica recomendada para que una aplicación en EC2 acceda a Amazon S3?',
 o:['Asignar un rol de IAM a la instancia','Incrustar claves de acceso en el código','Usar credenciales del usuario root','Hacer público el bucket'],a:0,
 why:'Los roles proporcionan credenciales temporales y rotadas automáticamente.'},
{d:2,q:'¿Qué DOS medidas debe aplicar una empresa al usuario root de su cuenta? (elige dos)',
 o:['Activar MFA','Usarlo solo para tareas que lo exijan','Crear claves de acceso permanentes','Compartirlo con todo el equipo'],a:[0,1],multi:true,
 why:'El root debe protegerse con MFA y reservarse para tareas específicas.'},
{d:2,q:'¿Qué servicio detecta amenazas analizando CloudTrail, VPC Flow Logs y registros DNS?',
 o:['Amazon GuardDuty','Amazon Inspector','AWS Shield','AWS Config'],a:0,
 why:'GuardDuty es el servicio de detección de amenazas gestionado de AWS.'},
{d:2,q:'¿Qué servicio identifica datos personales almacenados en Amazon S3?',
 o:['Amazon Macie','Amazon GuardDuty','AWS Artifact','Amazon Detective'],a:0,
 why:'Macie descubre y clasifica datos sensibles mediante machine learning.'},
{d:2,q:'¿Qué servicio protege aplicaciones web frente a inyección SQL y cross-site scripting?',
 o:['AWS WAF','AWS Shield Standard','Amazon Inspector','AWS KMS'],a:0,
 why:'WAF filtra el tráfico HTTP con reglas en la capa de aplicación.'},
{d:2,q:'¿Qué protección frente a DDoS está incluida sin coste adicional para todos los clientes de AWS?',
 o:['AWS Shield Standard','AWS Shield Advanced','AWS WAF','AWS Firewall Manager'],a:0,
 why:'Shield Standard protege automáticamente frente a los ataques más comunes de capa 3 y 4.'},
{d:2,q:'¿Dónde se obtienen los informes de cumplimiento SOC e ISO de AWS?',
 o:['AWS Artifact','AWS Config','AWS Trusted Advisor','AWS Security Hub'],a:0,
 why:'Artifact es el repositorio de autoservicio de informes de auditoría.'},
{d:2,q:'¿Qué servicio registra las llamadas a la API realizadas en una cuenta de AWS?',
 o:['AWS CloudTrail','Amazon CloudWatch','AWS Config','AWS X-Ray'],a:0,
 why:'CloudTrail responde a quién hizo qué, cuándo y desde qué dirección IP.'},
{d:2,q:'¿Qué servicio evalúa de forma continua si los recursos cumplen las reglas de configuración definidas?',
 o:['AWS Config','AWS CloudTrail','Amazon GuardDuty','AWS Systems Manager'],a:0,
 why:'Config mantiene el historial de configuración y evalúa la conformidad.'},
{d:2,q:'Una empresa necesita HSM dedicados de un solo cliente para cumplir una normativa. ¿Qué servicio usa?',
 o:['AWS CloudHSM','AWS KMS','AWS Secrets Manager','AWS Certificate Manager'],a:0,
 why:'CloudHSM ofrece módulos de hardware dedicados con control exclusivo del cliente.'},
{d:2,q:'¿Qué servicio genera y renueva automáticamente certificados TLS para su uso con ELB o CloudFront?',
 o:['AWS Certificate Manager','AWS KMS','Amazon Route 53','AWS IAM'],a:0,
 why:'ACM elimina la gestión manual de la renovación de certificados públicos.'},
{d:2,q:'En IAM, si una política permite una acción y otra la deniega explícitamente, ¿qué sucede?',
 o:['La acción se deniega','La acción se permite','Se aplica la política más reciente','Se solicita autorización al root'],a:0,
 why:'Un deny explícito siempre prevalece sobre cualquier allow.'},
{d:2,q:'¿Qué característica de un grupo de seguridad de VPC es correcta?',
 o:['Es con estado y solo admite reglas de permitir','Es sin estado y admite reglas de denegar','Se aplica a toda la subred','Sustituye a la tabla de rutas'],a:0,
 why:'Las NACL son sin estado, a nivel de subred y permiten reglas de denegar.'},
{d:2,q:'¿Qué servicio permite aplicar límites máximos de permisos a todas las cuentas de una unidad organizativa?',
 o:['Las SCP de AWS Organizations','Las políticas gestionadas de IAM','AWS Control Tower Guardrails de detección','Amazon Cognito'],a:0,
 why:'Las políticas de control de servicios definen el techo de permisos de las cuentas miembro.'},
{d:2,q:'¿Qué servicio almacena secretos como contraseñas de bases de datos y los rota automáticamente?',
 o:['AWS Secrets Manager','AWS KMS','AWS Artifact','Amazon Macie'],a:0,
 why:'Secrets Manager cifra los secretos con KMS y admite rotación programada.'},
{d:2,q:'¿Qué servicio ofrece una vista central del estado de seguridad agregando hallazgos de GuardDuty, Inspector y Macie?',
 o:['AWS Security Hub','AWS Config','Amazon Detective','AWS Firewall Manager'],a:0,
 why:'Security Hub centraliza hallazgos y comprobaciones de cumplimiento.'},
{d:2,q:'¿Qué servicio simplifica el acceso de los empleados a varias cuentas de AWS con su identidad corporativa?',
 o:['AWS IAM Identity Center','Amazon Cognito','AWS Directory Service para usuarios externos','AWS Organizations SCP'],a:0,
 why:'IAM Identity Center (antes AWS SSO) federa el acceso a múltiples cuentas.'},
{d:2,q:'¿Quién es responsable de clasificar y cifrar los datos que un cliente almacena en Amazon S3?',
 o:['El cliente','AWS','El auditor externo','El partner de AWS'],a:0,
 why:'Los datos del cliente son siempre responsabilidad del cliente.'},
{d:2,q:'¿Qué servicio busca vulnerabilidades conocidas en instancias EC2 y en imágenes de contenedor?',
 o:['Amazon Inspector','Amazon Macie','AWS Trusted Advisor','AWS Shield Advanced'],a:0,
 why:'Inspector realiza evaluaciones continuas de CVEs y exposición de red.'},
{d:2,q:'¿Qué servicio ayuda a investigar la causa raíz de un incidente de seguridad correlacionando registros?',
 o:['Amazon Detective','AWS CloudTrail Lake solamente','AWS Config','Amazon QuickSight'],a:0,
 why:'Detective construye gráficos de comportamiento a partir de los datos de la cuenta.'},
{d:2,q:'¿Qué herramienta identifica recursos accesibles desde fuera de la cuenta u organización?',
 o:['IAM Access Analyzer','AWS Budgets','Amazon Inspector','AWS Artifact'],a:0,
 why:'Access Analyzer detecta accesos externos no deseados en buckets, roles y claves.'},
{d:2,q:'¿Qué DOS elementos forman parte del principio de mínimo privilegio? (elige dos)',
 o:['Conceder solo los permisos necesarios para la tarea','Revisar y retirar permisos no utilizados','Dar acceso de administrador para evitar bloqueos','Compartir credenciales entre equipos'],a:[0,1],multi:true,
 why:'Mínimo privilegio implica conceder lo justo y revisarlo con regularidad.'},
{d:2,q:'¿Qué afirmación sobre el cifrado en AWS es correcta?',
 o:['El cliente decide qué datos cifra y con qué claves','AWS cifra siempre todo sin opción de configuración','El cifrado en tránsito no es posible en AWS','Solo se puede cifrar con claves de terceros'],a:0,
 why:'AWS ofrece las herramientas; la decisión y la configuración corresponden al cliente.'},

/* ---------------- Dominio 3 · Tecnología y servicios (34 %) ---------------- */
{d:3,q:'¿Qué es una zona de disponibilidad de AWS?',
 o:['Uno o más centros de datos aislados dentro de una Región','Un continente','Un rack de servidores','Una cuenta de AWS'],a:0,
 why:'Las AZ tienen alimentación, refrigeración y red independientes.'},
{d:3,q:'¿Qué DOS factores se consideran al elegir una Región de AWS? (elige dos)',
 o:['El cumplimiento normativo y la residencia de datos','La latencia hacia los usuarios finales','El idioma del soporte telefónico','El número de usuarios de IAM'],a:[0,1],multi:true,
 why:'Cumplimiento, latencia, precio y disponibilidad de servicios son los cuatro criterios.'},
{d:3,q:'Un trabajo de análisis por lotes tolera interrupciones y busca el mínimo coste. ¿Qué opción de compra de EC2 conviene?',
 o:['Instancias Spot','Instancias reservadas','Bajo demanda','Dedicated Hosts'],a:0,
 why:'Spot ofrece hasta un 90 % de descuento sobre el precio bajo demanda.'},
{d:3,q:'¿Qué servicio ejecuta código en respuesta a eventos sin aprovisionar servidores?',
 o:['AWS Lambda','Amazon EC2','Amazon Lightsail','AWS Batch'],a:0,
 why:'Lambda factura por solicitudes y por tiempo de ejecución.'},
{d:3,q:'¿Qué servicio ajusta automáticamente el número de instancias EC2 según la demanda?',
 o:['Amazon EC2 Auto Scaling','Elastic Load Balancing','Amazon CloudFront','AWS Config'],a:0,
 why:'Auto Scaling mantiene la capacidad deseada y responde a las métricas definidas.'},
{d:3,q:'¿Qué balanceador de carga conviene para tráfico HTTPS con enrutamiento basado en la ruta de la URL?',
 o:['Application Load Balancer','Network Load Balancer','Gateway Load Balancer','Classic Load Balancer para UDP'],a:0,
 why:'El ALB opera en capa 7 y admite reglas por host y por ruta.'},
{d:3,q:'¿Qué clase de Amazon S3 es la más económica para datos que se conservan años y casi nunca se recuperan?',
 o:['S3 Glacier Deep Archive','S3 Standard','S3 Standard-IA','S3 Intelligent-Tiering'],a:0,
 why:'Deep Archive es la opción de menor coste, con recuperación en horas.'},
{d:3,q:'¿Qué característica de S3 protege frente a borrados accidentales conservando copias anteriores?',
 o:['El versionado','El cifrado SSE-S3','La aceleración de transferencia','El bloqueo de acceso público'],a:0,
 why:'Con versionado, cada sobrescritura crea una nueva versión y conserva la anterior.'},
{d:3,q:'Varias instancias EC2 con Linux necesitan compartir el mismo sistema de archivos. ¿Qué servicio se usa?',
 o:['Amazon EFS','Amazon EBS','Instance Store','Amazon S3 Glacier'],a:0,
 why:'EFS es un sistema de archivos NFS elástico y compartido.'},
{d:3,q:'¿Qué servicio de base de datos es NoSQL, sin servidor y con latencia de milisegundos de un dígito?',
 o:['Amazon DynamoDB','Amazon RDS','Amazon Redshift','Amazon Aurora'],a:0,
 why:'DynamoDB escala automáticamente sin gestionar servidores.'},
{d:3,q:'¿Qué servicio es un almacén de datos para análisis de gran volumen con SQL?',
 o:['Amazon Redshift','Amazon DynamoDB','Amazon ElastiCache','Amazon Neptune'],a:0,
 why:'Redshift es el data warehouse columnar de AWS.'},
{d:3,q:'¿Qué opción de Amazon RDS proporciona alta disponibilidad con conmutación automática?',
 o:['Multi-AZ','Réplicas de lectura','Instantáneas automáticas','Grupos de parámetros'],a:0,
 why:'Multi-AZ mantiene una réplica en espera en otra zona de disponibilidad.'},
{d:3,q:'¿Qué servicio entrega contenido en caché desde ubicaciones de borde cercanas al usuario?',
 o:['Amazon CloudFront','Amazon Route 53','AWS Global Accelerator','Elastic Load Balancing'],a:0,
 why:'CloudFront es la red de entrega de contenido de AWS.'},
{d:3,q:'¿Qué servicio proporciona una conexión dedicada y privada entre las instalaciones del cliente y AWS?',
 o:['AWS Direct Connect','AWS Site-to-Site VPN','Amazon VPC Peering','AWS Transit Gateway'],a:0,
 why:'Direct Connect no atraviesa internet y ofrece ancho de banda constante.'},
{d:3,q:'¿Qué servicio permite consultar con SQL datos almacenados directamente en Amazon S3?',
 o:['Amazon Athena','Amazon Redshift Spectrum exclusivamente','AWS Glue','Amazon EMR'],a:0,
 why:'Athena es sin servidor y se factura por datos escaneados.'},
{d:3,q:'¿Qué servicio despliega recursos de AWS a partir de plantillas de infraestructura como código?',
 o:['AWS CloudFormation','AWS CodeDeploy','AWS Systems Manager','AWS Service Catalog'],a:0,
 why:'CloudFormation crea pilas repetibles a partir de plantillas YAML o JSON.'},
{d:3,q:'¿Qué servicio recopila métricas y activa alarmas sobre los recursos de AWS?',
 o:['Amazon CloudWatch','AWS CloudTrail','AWS Config','AWS Trusted Advisor'],a:0,
 why:'CloudWatch es la plataforma de monitorización y observabilidad.'},
{d:3,q:'¿Qué servicio es un orquestador de contenedores Kubernetes gestionado?',
 o:['Amazon EKS','Amazon ECS','AWS Fargate','Amazon ECR'],a:0,
 why:'EKS ejecuta Kubernetes gestionado; ECS es el orquestador propio de AWS.'},
{d:3,q:'¿Qué servicio ejecuta contenedores sin que el cliente gestione servidores?',
 o:['AWS Fargate','Amazon EC2','Amazon Lightsail','AWS Outposts'],a:0,
 why:'Fargate es el motor de cómputo sin servidor para ECS y EKS.'},
{d:3,q:'Una empresa necesita transferir 100 TB desde una ubicación con poco ancho de banda. ¿Qué opción es adecuada?',
 o:['AWS Snowball Edge','Carga directa por internet a S3','Amazon EFS','AWS Direct Connect en un día'],a:0,
 why:'La familia Snow traslada físicamente los datos cuando la red no es viable.'},
{d:3,q:'¿Qué servicio permite desacoplar componentes mediante colas de mensajes?',
 o:['Amazon SQS','Amazon SNS','AWS Step Functions','Amazon EventBridge'],a:0,
 why:'SQS almacena los mensajes hasta que un consumidor los procesa.'},
{d:3,q:'¿Qué servicio convierte texto en voz con sonido natural?',
 o:['Amazon Polly','Amazon Transcribe','Amazon Comprehend','Amazon Rekognition'],a:0,
 why:'Polly hace text-to-speech; Transcribe hace lo contrario.'},
{d:3,q:'¿Qué servicio proporciona servidores virtuales sencillos a precio mensual fijo?',
 o:['Amazon Lightsail','Amazon EC2 bajo demanda','AWS Fargate','AWS Batch'],a:0,
 why:'Lightsail empaqueta cómputo, almacenamiento y red en planes predecibles.'},
{d:3,q:'¿Qué servicio ayuda a analizar el rendimiento de aplicaciones distribuidas rastreando las peticiones?',
 o:['AWS X-Ray','Amazon CloudWatch Metrics','AWS Config','AWS CloudTrail'],a:0,
 why:'X-Ray traza extremo a extremo el recorrido de una petición.'},
{d:3,q:'¿Qué servicio proporciona DNS gestionado y registro de dominios?',
 o:['Amazon Route 53','Amazon CloudFront','AWS Direct Connect','Elastic Load Balancing'],a:0,
 why:'Route 53 resuelve nombres y admite políticas de enrutamiento avanzadas.'},
{d:3,q:'¿Qué DOS afirmaciones sobre AWS Lambda son correctas? (elige dos)',
 o:['Se factura por número de solicitudes y duración','Escala automáticamente con la carga','Requiere aprovisionar instancias EC2','Necesita un balanceador de carga obligatorio'],a:[0,1],multi:true,
 why:'Lambda es totalmente gestionado y escala de cero a miles de ejecuciones concurrentes.'},

/* ---------------- Dominio 4 · Facturación y soporte (12 %) ---------------- */
{d:4,q:'¿Qué servicio permite visualizar y analizar el gasto de AWS a lo largo del tiempo?',
 o:['AWS Cost Explorer','AWS Pricing Calculator','AWS Artifact','AWS Config'],a:0,
 why:'Cost Explorer analiza el gasto histórico y ofrece previsiones y recomendaciones.'},
{d:4,q:'¿Qué servicio avisa cuando el gasto o el uso supera un umbral establecido?',
 o:['AWS Budgets','AWS Cost Explorer','Amazon CloudWatch Logs','AWS Trusted Advisor'],a:0,
 why:'Budgets permite definir presupuestos y alertas por correo o SNS.'},
{d:4,q:'¿Qué plan de soporte incluye un Technical Account Manager designado?',
 o:['Enterprise','Business','Developer','Basic'],a:0,
 why:'Enterprise asigna un TAM; Enterprise On-Ramp da acceso a un grupo de TAM.'},
{d:4,q:'¿Cuál es el plan de soporte mínimo que ofrece atención 24/7 por teléfono, chat y correo?',
 o:['Business','Developer','Basic','Enterprise'],a:0,
 why:'Developer solo ofrece soporte por correo en horario laboral.'},
{d:4,q:'¿Qué ventaja aporta la facturación consolidada de AWS Organizations?',
 o:['Una única factura y descuentos por volumen agregados','Duplicar las cuotas de servicio','Soporte Enterprise sin coste','Cifrado automático de todos los datos'],a:0,
 why:'El uso agregado alcanza antes los tramos de precio más bajos.'},
{d:4,q:'¿Qué herramienta estima el coste de una arquitectura antes de desplegarla?',
 o:['AWS Pricing Calculator','AWS Cost Explorer','AWS Budgets','AWS Cost and Usage Report'],a:0,
 why:'La calculadora permite modelar servicios y comparar escenarios de coste.'},
{d:4,q:'¿Qué servicio revisa la cuenta y hace recomendaciones sobre coste, seguridad, rendimiento, tolerancia a fallos y cuotas?',
 o:['AWS Trusted Advisor','AWS Config','AWS Health Dashboard','AWS Artifact'],a:0,
 why:'Son las cinco categorías de comprobaciones de Trusted Advisor.'},
{d:4,q:'¿Dónde comprueba un cliente si un incidente de AWS afecta a sus recursos concretos?',
 o:['AWS Health Dashboard','AWS Trusted Advisor','Amazon CloudWatch','AWS Artifact'],a:0,
 why:'El Health Dashboard muestra eventos que afectan a la cuenta y al servicio.'},
{d:4,q:'¿Qué mecanismo permite repartir los costes de AWS por proyecto o departamento?',
 o:['Las etiquetas de asignación de costes','Las zonas de disponibilidad','Los grupos de seguridad','Las cuotas de servicio'],a:0,
 why:'Las cost allocation tags activadas aparecen en los informes de facturación.'},
{d:4,q:'¿Qué tipos de ofertas incluye la capa gratuita de AWS?',
 o:['Siempre gratis, 12 meses gratis y pruebas de corta duración','Solo pruebas de 30 días','Descuento del 50 % el primer año','Uso ilimitado de EC2'],a:0,
 why:'Son las tres modalidades del AWS Free Tier.'},
{d:4,q:'¿Qué opción de compra ofrece la mayor flexibilidad de descuento entre EC2, Fargate y Lambda?',
 o:['Compute Savings Plans','Instancias reservadas estándar','Spot','Dedicated Hosts'],a:0,
 why:'El Compute Savings Plan compromete un gasto por hora aplicable a varios servicios.'},
{d:4,q:'¿Dónde se adquiere software de terceros con facturación integrada en la cuenta de AWS?',
 o:['AWS Marketplace','AWS Artifact','AWS re:Post','AWS Partner Network'],a:0,
 why:'Marketplace es el catálogo digital de soluciones de terceros.'}
];

/* Distribución del examen real (65 preguntas): D1 24 %, D2 30 %, D3 34 %, D4 12 % */
const EXAM_CONFIG = { total: 65, minutes: 90, passScore: 70, mix: { 1: 16, 2: 19, 3: 22, 4: 8 } };
const DOMAIN_NAMES = {
  1: 'Conceptos de la nube',
  2: 'Seguridad y cumplimiento',
  3: 'Tecnología y servicios',
  4: 'Facturación y soporte'
};
EXAM_BANK.forEach((q, i) => { q.id = 'x' + i; q.multi = q.multi || Array.isArray(q.a); });
